### ISSUE TITLE
Any Additional Line of EXP Upon Killing A Mob Shows You Get The Proper EXP, but Does Not Add Said Amount Into EXP Bar

### ISSUE THREAD

**Issue by LeePNano** [bostonmak/ProjectNano2#121]
https://media.discordapp.net/attachments/365741881503776770/476807997537124353/unknown.png

**Comment by LeePNano** [comment]
When you are in a pt, the pt exp is not added to your exp, and neither is pendant of the spirit

**Comment by bostonmak** [comment]
[https://github.com/bostonmak/ProjectNano2/commit/d727fbc054be39060e7a48c7e342ce4e41c7b135](url)
