### ISSUE TITLE
Upon rebirth to mage and potentially other jobs, Total HP Resets

### ISSUE THREAD

**Issue by LeePNano** [bostonmak/ProjectNano2#127]
Laguz rebirthed into a mage, and his max hp is like 1000 something instead of adding 1000 to his max health.  He retained his total mana of liek 5k, but his total hp shoudl be like 6k or something

https://media.discordapp.net/attachments/365741881503776770/476973083203207178/unknown.png

https://media.discordapp.net/attachments/365741881503776770/476973142468722702/unknown.png

**Comment by minimucho1** [comment]
Is this really a bug? Shouldn't HP be reset upon rebirthing? Just give them the bonus HP? @lightryuzaki

**Comment by minimucho1** [comment]
Only bonus HP is supposed to carry over.
