### ISSUE TITLE
[Feature] Cygnus Knights can level over 120

### ISSUE THREAD

**Issue by minimucho1** [bostonmak/ProjectNano2#25]
@lightryuzaki had fixed the leveling cap issue via #20. 

We must now decide where to go from here. 

Resolution 1: Cygnus Knight do not receive SP past 120. And instead give them 6 SP per level instead of 5.
Resolution 2: Adjust their SP gain to 5 per level and allow them to "overlevel" their job adv at 120

**Comment by lightryuzaki** [comment]
They do not unfortunately level above 120

**Comment by minimucho1** [comment]
We will follow resolution 2

**Comment by minimucho1** [comment]
I think this is working?
