### ISSUE TITLE
[Feature] Rebirthing System

### ISSUE THREAD

**Issue by minimucho1** [bostonmak/ProjectNano2#28]
**Description:**
Rebirth Feature
* Reset character level to 1
* Refund all AP spent, to reapply
* Add `@rebirth` command
* Has a `Golden Maple Leaf` that will be consumed to rebirth

Character must meet these requirements to rebirth
* Be max level 200
* Have a `Golden Maple Leaf`

**Validation:**

GIVEN I have a character that is level 200 and has 1 `Golden Maple Leaf` to rebirth
WHEN a player uses the `@rebirth` command
THEN the player should be displayed a text box asking them what job they would like to rebirth into: Beginner, Noblesse, Legend

GIVEN a player has the rebirth text box displayed to them
WHEN a player selects a job to rebirth into and is successful
THEN the character should be set to level 1, have their AP refunded minus AP spent on HP/MP as well retain unspent AP, job changed to `selectedJob`, and have 1 `Golden Maple Leaf` removed from their inventory
AND
THEN a server notice will be displayed to all users "`characterName` has rebirthed! They have rebirthed `numberOfRebirths` time(s)!"

GIVEN I have a character that does not meet the level requirement
WHEN the player selects a job to rebirth into
THEN a message will be displayed that says "You cannot rebirth. You do not meet the level requirement to rebirth."

GIVEN I have a character that does not have the required items
WHEN the player selects a job to rebirth into
THEN a message will be displayed that says "You cannot rebirth. You are missing `numberOfRequiredItems` `nameOfRequiredItem`"

GIVEN a character has rebirthed for the first time and logged off
WHEN I query the `CHARACTERS` table in the SQL database
THEN I should see the `reborns` value getting updated

**Comment by lightryuzaki** [comment]
SP should not be reset when rebirthing ^^

**Comment by minimucho1** [comment]
Moved to Needs Validation

**Comment by minimucho1** [comment]
Validation criteria has been modified.

Players must be able to select a starting job upon rebirth. The following are available: `Beginner`, `Noblesse`, `Legend`

**Comment by minimucho1** [comment]
NPC added. Moved to Needs Validation.

**Comment by minimucho1** [comment]
Changing feature to not refund AP upon rebirthing. The player will instead retain their current stats.

**Comment by minimucho1** [comment]
Needs Validation @lightryuzaki @bostonmak
