### ISSUE TITLE
NPC 2100002 null pointer

### ISSUE THREAD

**Issue by lightryuzaki** [bostonmak/ProjectNano2#3]
![image](https://user-images.githubusercontent.com/32381002/39656990-8e35c32a-4fc9-11e8-8324-1e4ad4084c0e.png)

**Comment by minimucho1** [comment]
NPC 2100002
Name: Zaid
Location: The Burning Road: Ariant
Function: Weapon Seller

When clicking on him a stack trace is generated, but the code execution eventually calls the correct code to load the shop properly. This is also the case with NPC 2100003.

NPC 2100003
Name: Jasmine
Location: The Burning Road: Ariant
Function: Armor Seller

**Comment by minimucho1** [comment]
Waiting for validation @lightryuzaki @bostonmak
