### ISSUE TITLE
NPC9201001 Null Pointer 

### ISSUE THREAD

**Issue by lightryuzaki** [bostonmak/ProjectNano2#4]
![image](https://user-images.githubusercontent.com/32381002/39658961-a527a46c-4fe3-11e8-9b2b-f7fb215eec08.png)

**Comment by minimucho1** [comment]
NPC 9201001
Name: Nana(H)
Location: Henesys 
Function: Love Fairy

Cannot seem to reproduce the null pointer exception printed here? Is this still a valid bug?

@lightryuzaki Please elaborate further or validate if this is still a bug.

**Comment by lightryuzaki** [comment]
I believe this issue is can be closed
