### ISSUE TITLE
savetodb deadlocks?

### ISSUE THREAD

**Issue by lightryuzaki** [bostonmak/ProjectNano2#40]
https://images-ext-2.discordapp.net/external/UrTGetdAFZ2oJEkjXl6-vHjFBoz8872N5c42Vzm-dz0/https/i.gyazo.com/thumb/1200/ea00158823d9d2b87639fe74ce469b42-png.jpg?width=387&height=507

**Comment by lightryuzaki** [comment]
error message^

**Comment by minimucho1** [comment]
Closed with the new optimization. #45
