### ISSUE TITLE
Upon Rebirthing and 1st Job Adving Player's Stats Reset to 4

### ISSUE THREAD

**Issue by minimucho1** [bostonmak/ProjectNano2#42]

**Comment by minimucho1** [comment]
Can't seem to reproduce this on my end

**Comment by lightryuzaki** [comment]
Resolved

**Comment by minimucho1** [comment]
This bug is due to a player having rebirthed and then having their stats reset upon 1st job adv.

**Comment by lightryuzaki** [comment]
Upon rebirthing a player will speak to their first job instructor again, originally cm.resetstats was not with in the rebirth check if statement, Lee and I have both tested this function and it now will not reset your AP stats after rebirthing, it will still reset ap stats for characters who have not rebirthed. Working correctly.
