### ISSUE TITLE
Equip Inventory deleting itself + unable to login 

### ISSUE THREAD

**Issue by lightryuzaki** [bostonmak/ProjectNano2#7]
the resolution for the issue is listed at the bottom

**Comment by lightryuzaki** [comment]
![image](https://user-images.githubusercontent.com/32381002/39738831-25ea1140-5253-11e8-8155-65531ff025e4.png)

**Comment by lightryuzaki** [comment]
https://github.com/tylerhasman/MapleStory/blob/50e7a450cf630b8693e3480242cf08b47d263080/src/maplestory/player/MapleCharacter.java#L1506   the link posted for his maplecharacter

**Comment by bostonmak** [comment]
#36
